export const actionTypes = {
  STAKEHOLDERS: {
    FETCH_REQUEST: "STAKEHOLDERS_FETCH_REQUEST",
    FETCH_SUCCESS: "STAKEHOLDERS_FETCH_SUCCESS",
    FETCH_FAILURE: "STAKEHOLDERS_FETCH_FAILURE",
  },
  CATEGORIES: {
    FETCH_REQUEST: "CATEGORIES_FETCH_REQUEST",
    FETCH_SUCCESS: "CATEGORIES_FETCH_SUCCESS",
    FETCH_FAILURE: "CATEGORIES_FETCH_FAILURE",
  },
  UPDATE_CRITERIA: "UPDATE_CRITERIA",
  TOGGLE_SEARCH_PANEL: "TOGGLE_SEARCH_PANEL",
};
