export const actionTypes = {
  STAKEHOLDERS: {
    FETCH_REQUEST: "STAKEHOLDERS_FETCH_REQUEST",
    FETCH_SUCCESS: "STAKEHOLDERS_FETCH_SUCCESS",
    FETCH_FAILURE: "STAKEHOLDERS_FETCH_FAILURE",
  },
  CATEGORIES: {
    FETCH_REQUEST: "CATEGORIES_FETCH_REQUEST",
    FETCH_SUCCESS: "CATEGORIES_FETCH_SUCCESS",
    FETCH_FAILURE: "CATEGORIES_FETCH_FAILURE",
  },
  UPDATE: {
    LONGITUDE: "UPDATE_LONGITUDE",
    LATITUDE: "UPDATE_LATITUDE",
    DISTANCE: "UPDATE_DISTANCE",
    CATEGORIES: "UPDATE_CATEGORIES",
    SEARCH_STRING: "UPDATE_SEARCH_STRING",
  },
  TOGGLE_SEARCH_PANEL: "TOGGLE_SEARCH_PANEL",
};
