export const initialState = {
  isLoading: false,
  categoriesError: null,
  stakeholdersError: null,
  locationError: null,
  isSearchPanelOpen: false,
  stakeholders: [],
  categories: [],
  searchString: "",
  selectedCategories: null,
  latitude: null,
  longitude: null,
  selectedLatitude: 34.041001,
  selectedLongitude: -118.235036,
  selectedLocationName: "LACI",
  selectedDistance: 10,
};
