export const MAPBOX_STYLE = "mapbox://styles/mapbox/streets-v11";

export const FOOD_PANTRY_CATEGORY_ID = 1;
export const MEAL_PROGRAM_CATEGORY_ID = 9;
export const DEFAULT_CATEGORIES = [
  FOOD_PANTRY_CATEGORY_ID,
  MEAL_PROGRAM_CATEGORY_ID,
];

export const ORGANIZATION_LABELS = {
  [FOOD_PANTRY_CATEGORY_ID]: "Food Pantry",
  [MEAL_PROGRAM_CATEGORY_ID]: "Meal",
};

export const ORGANIZATION_COLORS = {
  [FOOD_PANTRY_CATEGORY_ID]: "#336699",
  [MEAL_PROGRAM_CATEGORY_ID]: "#CC3333",
};
