import * as yup from "yup";

export const STAKEHOLDER_SCHEMA = [
  {
    name: "id",
    label: "ID",
    description: "Stakeholder ID (leave blank for new entries)",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
    validation: null,
    validationMessage: "",
  },
  {
    name: "name",
    label: "Name",
    description: "Name of stakeholder",
    required: true,
    default_value: "",
    show: true,
    sample_format: "",
    validation: yup.string().required(),
    validationMessage: "",
  },
  {
    name: "address1",
    label: "Address 1",
    description: "",
    required: true,
    default_value: "",
    show: true,
    sample_format: "",
    validation: yup.string().required(),
    validationMessage: "",
  },
  {
    name: "address2",
    label: "Address 2",
    description: "",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "city",
    label: "City",
    description: "City as listed",
    required: true,
    default_value: "",
    show: true,
    sample_format: "",
    validation: yup.string().required(),
    validationMessage: "",
  },
  {
    name: "state",
    label: "State",
    description: "State as listed",
    required: true,
    default_value: "",
    show: true,
    sample_format: "",
    validation: yup.string().required(),
    validationMessage: "",
  },
  {
    name: "zip",
    label: "Zip",
    description: "Zip as listed",
    required: true,
    default_value: "",
    show: true,
    sample_format: "",
    validation: yup.string().required(),
    validationMessage: "",
  },
  {
    name: "phone",
    label: "Phone",
    description: "Phone as listed",
    required: true,
    default_value: "",
    show: true,
    sample_format: "(xxx)xxx-xxxx",
    validation: yup.string().required(),
    validationMessage: "",
  },
  {
    name: "latitude",
    label: "Latitude",
    description: "",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
    validation: yup.number(),
    validationMessage: "",
  },
  {
    name: "longitude",
    label: "Longitude",
    description: "",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
    validation: yup.number(),
    validationMessage: "",
  },
  {
    name: "website",
    label: "Website",
    description: "",
    required: false,
    default_value: "",
    show: true,
    sample_format: "https://foodoasis.la",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "fmId",
    label: "FM ID",
    description: "",
    required: false,
    default_value: "",
    show: false,
    sample_format: "",
  },
  {
    name: "notes",
    label: "Notes",
    description: "",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "createdDate",
    label: "Created Date",
    description: "",
    required: false,
    default_value: "",
    show: false,
    sample_format: "",
  },
  {
    name: "createdLoginId",
    label: "Created Login ID",
    description: "ID of user who created record",
    required: false,
    default_value: "Auto",
    show: false,
    sample_format: 101,
  },
  {
    name: "modifiedDate",
    label: "Modified Date",
    description: "",
    required: false,
    default_value: "",
    show: false,
    sample_format: "",
  },
  {
    name: "modifiedLoginId",
    label: "Modified Login ID",
    description: "ID of user who modified record",
    required: false,
    default_value: "",
    show: false,
    sample_format: "",
  },
  {
    name: "submittedDate",
    label: "Submitted Date",
    description: "",
    required: false,
    default_value: "",
    show: false,
    sample_format: "",
  },
  {
    name: "submittedLoginId",
    label: "Submitted Login ID",
    description: "ID of user who submitted record",
    required: true,
    default_value: "",
    show: false,
    sample_format: "",
  },
  {
    name: "requirements",
    label: "Requirements",
    description: "",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "adminNotes",
    label: "Admin Notes",
    description: "",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "inactive",
    label: "Inactive",
    description: "",
    required: false,
    default_value: "f",
    show: true,
    sample_format: "",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "parentOrganization",
    label: "Parent Organization",
    description: "",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "physicalAccess",
    label: "Physical Access",
    description: "",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "email",
    label: "Email",
    description: "Stakeholder's email",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "items",
    label: "Items",
    description: "",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
  },
  {
    name: "services",
    label: "Services",
    description: "",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
  },
  {
    name: "facebook",
    label: "Facebook",
    description: "Stakeholder's Facebook URL",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "twitter",
    label: "Twitter",
    description: "Stakeholder's Twitter handle",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "pinterest",
    label: "Pinterest",
    description: "Stakeholder's Pinterest URL",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "linkedin",
    label: "LinkedIn",
    description: "Stakeholder's LinkedIn URL",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "description",
    label: "Description",
    description: "",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "approvedDate",
    label: "Approved Date",
    description: "",
    required: false,
    default_value: "",
    show: false,
    sample_format: "",
  },
  {
    name: "reviewedLoginId",
    label: "Reviewed Login ID",
    description: "ID of user who reviewed stakeholder",
    required: false,
    default_value: "",
    show: false,
    sample_format: "",
  },
  {
    name: "assignedLoginId",
    label: "Assigned Login ID",
    description: "ID of user who is assigned to stakeholder",
    required: false,
    default_value: "",
    show: false,
    sample_format: "",
  },
  {
    name: "agencyType",
    label: "Agency Type",
    description: "",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
  },
  {
    name: "assignedDate",
    label: "Assigned Date",
    description: "",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
  },
  {
    name: "reviewNotes",
    label: "Review Notes",
    description: "",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
  },
  {
    name: "claimedLoginId",
    label: "Claimed Login ID",
    description: "",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
  },
  {
    name: "claimedDate",
    label: "Claimed Date",
    description: "",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
  },
  {
    name: "instagram",
    label: "Instagram",
    description: "Stakeholder's Instagram handle",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
  },
  {
    name: "adminContactName",
    label: "Admin Contact Name",
    description: "",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
  },
  {
    name: "adminContactPhone",
    label: "Admin Contact Phone",
    description: "",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
  },
  {
    name: "adminContactEmail",
    label: "Admin Contact Email",
    description: "",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
  },
  {
    name: "donationContactName",
    label: "Donation Contact Name",
    description: "",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "donationContactPhone",
    label: "Donation Contact Phone",
    description: "",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "donationContactEmail",
    label: "Donation Contact Email",
    description: "",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "donationPickup",
    label: "Donation Pickup",
    description: "",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "donationAcceptFrozen",
    label: "Donation Accept Frozen",
    description: "",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "donationAcceptRefrigerated",
    label: "Donation Accept Refrigerated",
    description: "",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "donationAcceptPerishable",
    label: "Donation Accept Perishable",
    description: "",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "donationSchedule",
    label: "Donation Schedule",
    description: "",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "donationDeliveryInstructions",
    label: "Donation Delivery Instructions",
    description: "",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "covidNotes",
    label: "COVID Notes",
    description: "",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "donationNotes",
    label: "Donation Notes",
    description: "",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "categoryNotes",
    label: "Category Notes",
    description: "",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "eligibilityNotes",
    label: "Eligibility Notes",
    description: "",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "foodTypes",
    label: "Food Types",
    description: "",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
  },
  {
    name: "languages",
    label: "Languages",
    description: "",
    required: false,
    default_value: "English",
    show: true,
    sample_format: "",
  },
  {
    name: "confirmedName",
    label: "",
    description: "",
    required: false,
    default_value: "f",
    show: true,
    sample_format: "f",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "confirmedCategories",
    label: "",
    description: "",
    required: false,
    default_value: "f",
    show: true,
    sample_format: "f",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "confirmedAddress",
    label: "",
    description: "",
    required: false,
    default_value: "f",
    show: true,
    sample_format: "f",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "confirmedPhone",
    label: "",
    description: "",
    required: false,
    default_value: "f",
    show: true,
    sample_format: "f",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "confirmedEmail",
    label: "",
    description: "",
    required: false,
    default_value: "f",
    show: true,
    sample_format: "f",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "confirmedHours",
    label: "",
    description: "",
    required: false,
    default_value: "f",
    show: true,
    sample_format: "f",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "confirmedFoodTypes",
    label: "",
    description: "",
    required: false,
    default_value: "f",
    show: true,
    sample_format: "f",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "verificationStatusId",
    label: "Verification Status ID",
    description: "",
    required: false,
    default_value: "1",
    show: true,
    sample_format: "",
  },
  {
    name: "inactiveTemporary",
    label: "Inactive Temporary",
    description: "",
    required: false,
    default_value: "f",
    show: true,
    sample_format: "",
  },
  {
    name: "hours",
    label: "Hours",
    description:
      "Hours of operation. (week of month, day of week, open time, close time). \nIf Hours is populated, don't fill out Week Hours columns.",
    required: false,
    default_value: "",
    show: true,
    sample_format:
      "(3,Fri,10:00,13:00),\n(1,Sat,10:00,13:00),\n(1,Fri 10:00,13:00),\n (3,Sat,10:00,13:00)",
  },
  {
    name: "hoursWeek1",
    label: "Week 1 Hours",
    description:
      "Hours of operation (1st week of month). (day of week, open time, close time). \nIf Week Hours are populated, don't fill out Hours column.",
    required: false,
    default_value: "",
    show: true,
    sample_format: "(Fri,10:00,13:00),\n(Sat,10:00,13:00)",
  },
  {
    name: "hoursWeek2",
    label: "Week 2 Hours",
    description:
      "Hours of operation (2nd week of month). (day of week, open time, close time). \nIf Week Hours are populated, don't fill out Hours column.",
    required: false,
    default_value: "",
    show: true,
    sample_format: "(Fri,10:00,13:00),\n(Sat,10:00,13:00)",
  },
  {
    name: "hoursWeek3",
    label: "Week 3 Hours",
    description:
      "Hours of operation (3rd week of month). (day of week, open time, close time). \nIf Week Hours are populated, don't fill out Hours column.",
    required: false,
    default_value: "",
    show: true,
    sample_format: "(Tue,10:00,13:00),\n(Thu,10:00,13:00)",
  },
  {
    name: "hoursWeek4",
    label: "Week 4 Hours",
    description:
      "Hours of operation (4th week of month). (day of week, open time, close time). \nIf Week Hours are populated, don't fill out Hours column.",
    required: false,
    default_value: "",
    show: true,
    sample_format: "(Mon,10:00,13:00),\n(Wed,10:00,13:00),\n(Fri,10:00,13:00)",
  },
  {
    name: "hoursWeekLast",
    label: "Last Week Hours",
    description:
      "Hours of operation (Last week of month). (day of week, open time, close time). \nIf Week Hours are populated, don't fill out Hours column.",
    required: false,
    default_value: "",
    show: true,
    sample_format: "(Sun,10:00,13:00)",
  },
  {
    name: "selectedCategoryIds",
    label: "Selected Category IDs",
    description:
      "Category of stakeholder. May be one or multiple values. Use numbers (eg. 1,2,5) to assign categories \n1. Food Pantry, \n2. Community Garden, \n4. Farmer's Market, \n5. Supermarket, \n6. Summer Lunch for Kids\n7. Care Center,\n8. Food Bank,\n9. Meal Program,\n10. Shelter,\n11. Other,\n12. Unknown",
    required: true,
    default_value: "1",
    show: true,
    sample_format: "1,2,5",
    validation: yup.array().of(yup.string()).required(),
    validationMessage: "",
  },
  {
    name: "neighborhoodId",
    label: "Neighborhood ID",
    description: "",
    required: false,
    default_value: "",
    show: true,
    sample_format: "",
  },
  {
    name: "completeCriticalPercent",
    label: "Complete Critical Percent",
    description: "",
    required: false,
    default_value: "",
    show: false,
    sample_format: "",
  },
  {
    name: "foodBakery",
    label: "Food Bakery",
    description: "t or f whether provided by stakeholder",
    required: false,
    default_value: "f",
    show: true,
    sample_format: "f",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "foodDryGoods",
    label: "Food Dry Goods",
    description: "t or f whether provided by stakeholder",
    required: false,
    default_value: "f",
    show: true,
    sample_format: "f",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "foodProduce",
    label: "Food Produce",
    description: "t or f whether provided by stakeholder",
    required: false,
    default_value: "f",
    show: true,
    sample_format: "f",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "foodDairy",
    label: "Food Dairy",
    description: "t or f whether provided by stakeholder",
    required: false,
    default_value: "f",
    show: true,
    sample_format: "f",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "foodPrepared",
    label: "Food Prepared",
    description: "t or f whether provided by stakeholder",
    required: false,
    default_value: "f",
    show: true,
    sample_format: "f",
    validation: yup.string(),
    validationMessage: "",
  },
  {
    name: "foodMeat",
    label: "Food Meat",
    description: "t or f whether provided by stakeholder",
    required: false,
    default_value: "f",
    show: true,
    sample_format: "f",
    validation: yup.string(),
    validationMessage: "",
  },
];
