export const STAKEHOLDER_SCHEMA = [
  {
    name: "name",
    label: "Name",
    description: "Name of stakeholder",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "address_1",
    label: "Address 1",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "address_2",
    label: "Address 2",
    description: "",
    required: "No",
    default_value: "",
    sample_format: "",
  },
  {
    name: "city",
    label: "City",
    description: "City as listed",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "state",
    label: "State",
    description: "State as listed",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "zip",
    label: "Zip",
    description: "Zip as listed",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "phone",
    label: "Phone",
    description: "Phone as listed",
    required: "Yes",
    default_value: "",
    sample_format: "(xxx)xxx-xxxx",
  },
  {
    name: "latitude",
    label: "Latitude",
    description: "",
    required: "No",
    default_value: "",
    sample_format: "",
  },
  {
    name: "longitude",
    label: "Longitude",
    description: "",
    required: "No",
    default_value: "",
    sample_format: "",
  },
  {
    name: "website",
    label: "Website",
    description: "",
    required: "No",
    default_value: "",
    sample_format: "https://foodoasis.la",
  },
  {
    name: "fm_id",
    label: "FM ID",
    description: "",
    required: "No",
    default_value: "",
    sample_format: "",
  },
  {
    name: "notes",
    label: "Notes",
    description: "",
    required: "No",
    default_value: "",
    sample_format: "",
  },
  {
    name: "created_date",
    label: "Created Date",
    description: "",
    required: "No",
    default_value: "",
    sample_format: "",
  },
  {
    name: "created_login_id",
    label: "Created Login ID",
    description: "ID of user who created record",
    required: "No",
    default_value: "Auto",
    sample_format: 101,
  },
  {
    name: "modified_date",
    label: "Modified Date",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "modified_login_id",
    label: "Modified Login ID",
    description: "ID of user who modified record",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "submitted_date",
    label: "Submitted Date",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "submitted_login_id",
    label: "Submitted Login ID",
    description: "ID of user who submitted record",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "requirements",
    label: "Requirements",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "admin_notes",
    label: "Admin Notes",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "inactive",
    label: "Inactive",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "parent_organization",
    label: "Parent Organization",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "physical_access",
    label: "Physical Access",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "email",
    label: "Email",
    description: "Stakeholder's email",
    required: "No",
    default_value: "",
    sample_format: "",
  },
  {
    name: "items",
    label: "Items",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "services",
    label: "Services",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "facebook",
    label: "Facebook",
    description: "Stakeholder's Facebook URL",
    required: "No",
    default_value: "",
    sample_format: "",
  },
  {
    name: "twitter",
    label: "Twitter",
    description: "Stakeholder's Twitter handle",
    required: "No",
    default_value: "",
    sample_format: "",
  },
  {
    name: "pinterest",
    label: "Pinterest",
    description: "Stakeholder's Pinterest URL",
    required: "No",
    default_value: "",
    sample_format: "",
  },
  {
    name: "linkedin",
    label: "LinkedIn",
    description: "Stakeholder's LinkedIn URL",
    required: "No",
    default_value: "",
    sample_format: "",
  },
  {
    name: "description",
    label: "Description",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "approved_date",
    label: "Approved Date",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "reviewed_login_id",
    label: "Reviewed Login ID",
    description: "ID of user who reviewed stakeholder",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "assigned_login_id",
    label: "Assigned Login ID",
    description: "ID of user who is assigned to stakeholder",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "agency_type",
    label: "Agency Type",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "assigned_date",
    label: "Assigned Date",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "review_notes",
    label: "Review Notes",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "claimed_login_id",
    label: "Claimed Login ID",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "claimed_date",
    label: "Claimed Date",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "instagram",
    label: "Instagram",
    description: "Stakeholder's Instagram handle",
    required: "No",
    default_value: "",
    sample_format: "",
  },
  {
    name: "admin_contact_name",
    label: "Admin Contact Name",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "admin_contact_phone",
    label: "Admin Contact Phone",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "admin_contact_email",
    label: "Admin Contact Email",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "donation_contact_name",
    label: "Donation Contact Name",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "donation_contact_phone",
    label: "Donation Contact Phone",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "donation_contact_email",
    label: "Donation Contact Email",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "donation_pickup",
    label: "Donation Pickup",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "donation_accept_frozen",
    label: "Donation Accept Frozen",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "donation_accept_refrigerated",
    label: "Donation Accept Refrigerated",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "donation_accept_perishable",
    label: "Donation Accept Perishable",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "donation_schedule",
    label: "Donation Schedule",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "donation_delivery_instructions",
    label: "Donation Delivery Instructions",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "covid_notes",
    label: "COVID Notes",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "donation_notes",
    label: "Donation Notes",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "category_notes",
    label: "Category Notes",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "eligibility_notes",
    label: "Eligibility Notes",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "food_types",
    label: "Food Types",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "languages",
    label: "Languages",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "v_name",
    label: "V Name",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "v_categories",
    label: "V Categories",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "v_address",
    label: "V Address",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "v_email",
    label: "V Email",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "v_phone",
    label: "V Phone",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "v_hours",
    label: "V Hours",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "v_food_types",
    label: "V Food Types",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "verification_status_id",
    label: "Verification Status ID",
    description: "",
    required: "Yes",
    default_value: "1",
    sample_format: "",
  },
  {
    name: "inactive_temporary",
    label: "Inactive Temporary",
    description: "",
    required: "Yes",
    default_value: "f",
    sample_format: "",
  },
  {
    name: "hours",
    label: "Hours",
    description:
      "Hours of operation. Format = (week of month, day of week, open time, close time)",
    required: "Yes",
    default_value: "---",
    sample_format:
      "(3,Fri,10:00:00,13:00:00),\n(1,Sat,10:00:00,13:00:00),\n(1,Fri 10:00:00,13:00:00),\n (3,Sat,10:00:00,13:00:00)",
  },
  {
    name: "category_ids",
    label: "Category IDs",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "neighborhood_id",
    label: "Neighborhood ID",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "complete_critical_percent",
    label: "Complete Critical Percent",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "tenant_id",
    label: "Tenant ID",
    description:
      "ID of the tenant who is hosting the food oasis service (1 = LA, 2 = CA, 3 = HI",
    required: "Yes",
    default_value: "",
    sample_format: 1,
  },
  {
    name: "food_bakery",
    label: "Food Bakery",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "food_dry_goods",
    label: "Food Dry Goods",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "food_produce",
    label: "Food Produce",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "food_dairy",
    label: "Food Dairy",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "food_prepared",
    label: "Food Prepared",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
  {
    name: "food_meat",
    label: "Food Meat",
    description: "",
    required: "Yes",
    default_value: "",
    sample_format: "",
  },
];
