import { Page } from "@playwright/test";

export default async function mockRequests(
  page: Page,
  overrides?: Record<string, any>
) {
  const mocks = {
    ...MOCKS,
    ...overrides,
  }

  Object.entries(mocks).forEach(([path, response]) => {
    const handler = typeof response === "function" ? response : () => response;

    page.route(`**/api/${path}**`, (route) => {
      const mockResponse = handler();

      route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify(mockResponse),
      });
    });
  })
}

const MOCKS = {
  "accounts/confirmRegister": {
    isSuccess: true,
    message: "Email confirmed successfully",
  },
  "accounts/login": makeLoginResponse(),
  "accounts/resendConfirmationEmail": {
      isSuccess: true,
      code: "REG_SUCCESS",
      newId: "id",
      message: "Account found.",
    },
  "features": [
    {
      id: 1,
      name: "advancedFilter",
      is_enabled: true,
    },
  ],
  "stakeholderbests/select-all": makeStakeholdersResponse(),
};

function makeLoginResponse() {
  return {
    isSuccess: true,
    token: "token123",
    user: {
      id: 108,
      firstName: "Test",
      lastName: "User",
      email: "test@dispostable.com",
      emailConfirmed: true,
      passwordHash: "123",
      dateCreated: "2020-04-17T05:46:43.603Z",
      isGlobalAdmin: true,
      isGlobalReporting: false,
      tenantId: 1,
      isAdmin: true,
      isSecurityAdmin: false,
      isDataEntry: true,
      isCoordinator: false,
      features: ["advancedFilter"],
      role: "admin,data_entry,global_admin",
    },
  };
}

function makeStakeholdersResponse() {
  return [
    {
      id: 1,
      name: "Stakeholder 1",
      address1: "111 Address",
      address2: "",
      city: "City1",
      state: "CA",
      zip: "12345",
      phone: "(123) 456-1234",
      phoneExt: null,
      latitude: "33.79178035",
      longitude: "-118.3186286",
      website: "",
      notes: "",
      createdDate: "2020-03-30T01:39:28",
      modifiedDate: null,
      approvedDate: null,
      requirements: "",
      inactive: false,
      parentOrganization: "",
      physicalAccess: "",
      email: "",
      items: "",
      services: "",
      facebook: "http://localhost:3000",
      twitter: "http://localhost:3000",
      pinterest: "http://localhost:3000",
      linkedin: "http://localhost:3000",
      description: "",
      reviewNotes: "",
      instagram: "",
      adminContactName: "",
      adminContactPhone: "",
      adminContactEmail: "",
      covidNotes: "",
      foodTypes: "",
      hours: [
        {
          week_of_month: 0,
          day_of_week: "Mon",
          open: "00:00:00",
          close: "23:59:59",
        },
        {
          week_of_month: 0,
          day_of_week: "Tue",
          open: "00:00:00",
          close: "23:59:59",
        },
        {
          week_of_month: 0,
          day_of_week: "Wed",
          open: "00:00:00",
          close: "23:59:59",
        },
        {
          week_of_month: 0,
          day_of_week: "Thu",
          open: "00:00:00",
          close: "23:59:59",
        },
        {
          week_of_month: 0,
          day_of_week: "Sat",
          open: "00:00:00",
          close: "23:59:59",
        },
        {
          week_of_month: 0,
          day_of_week: "Sun",
          open: "00:00:00",
          close: "23:59:59",
        },
      ],
      languages: "English",
      verificationStatusId: 1,
      inactiveTemporary: false,
      categoryIds: [1, 9],
      neighborhoodId: null,
      neighborhoodName: null,
      isVerified: false,
      parentOrganizationId: null,
      allowWalkins: true,
      hoursNotes: "",
      tags: null,
      categories: [
        {
          id: 1,
          name: "Food Pantry",
          displayOrder: 10,
          isForFoodSeeker: true,
        },
        {
          id: 9,
          name: "Meal Program",
          displayOrder: 15,
          isForFoodSeeker: true,
        },
      ],
    },

    {
      id: 4408,
      name: "Stakeholder 2",
      address1: "222 Address",
      address2: "",
      city: "City2",
      state: "CA",
      zip: "12345",
      phone: "(123) 456-1234",
      phoneExt: null,
      latitude: "33.86091113",
      longitude: "-117.8743636",
      website: "",
      notes: "",
      createdDate: "2020-03-30T01:39:28",
      modifiedDate: null,
      approvedDate: null,
      requirements: "",
      inactive: false,
      parentOrganization: "",
      physicalAccess: "",
      email: "",
      items: "",
      services: "",
      facebook: "",
      twitter: "",
      pinterest: "",
      linkedin: "",
      description: "",
      reviewNotes: "",
      instagram: "",
      adminContactName: "",
      adminContactPhone: "",
      adminContactEmail: "",
      covidNotes: "",
      foodTypes: "",
      languages: "English",
      verificationStatusId: 1,
      inactiveTemporary: false,
      hours: null,
      categoryIds: [1],
      neighborhoodId: null,
      neighborhoodName: null,
      isVerified: false,
      parentOrganizationId: null,
      allowWalkins: false,
      hoursNotes: "",
      tags: null,
      categories: [
        {
          id: 1,
          name: "Food Pantry",
          displayOrder: 10,
          isForFoodSeeker: true,
        },
      ],
    },
    {
      id: 4387,
      name: "Stakeholder 3",
      address1: "333 Address",
      address2: "",
      city: "City3",
      state: "CA",
      zip: "12345",
      phone: "(123) 456-1234",
      phoneExt: null,
      latitude: "33.643773",
      longitude: "-117.721467",
      website: "",
      notes: "",
      createdDate: "2020-03-30T01:39:28",
      modifiedDate: null,
      approvedDate: null,
      requirements: "",
      inactive: false,
      parentOrganization: "",
      physicalAccess: "",
      email: "",
      items: "",
      services: "",
      facebook: "",
      twitter: "",
      pinterest: "",
      linkedin: "",
      description: "",
      reviewNotes: "",
      instagram: "",
      adminContactName: "",
      adminContactPhone: "",
      adminContactEmail: "",
      covidNotes: "",
      foodTypes: "",
      languages: "English",
      verificationStatusId: 1,
      inactiveTemporary: false,
      hours: null,
      categoryIds: [9],
      neighborhoodId: null,
      neighborhoodName: null,
      isVerified: false,
      parentOrganizationId: null,
      allowWalkins: false,
      hoursNotes: "",
      tags: null,
      categories: [
        {
          id: 9,
          name: "Meal Program",
          displayOrder: 15,
          isForFoodSeeker: true,
        },
      ],
    },
  ];
}
