import {
  Add,
  ArrowDownward,
  ArrowUpward,
  Cancel,
  Check,
  Close,
  Delete,
  Details,
  Edit,
  LocationOn,
  LocationSearching,
  Menu,
  Remove,
  Save,
  Search,
  WrapText,
} from "@mui/icons-material";

export const ICON_DICT = {
  add: Add,
  arrowUp: ArrowUpward,
  arrowDown: ArrowDownward,
  cancel: Cancel,
  check: Check,
  close: Close,
  delete: Delete,
  details: Details,
  edit: Edit,
  locationOn: LocationOn,
  locationSearching: LocationSearching,
  menu: Menu,
  remove: Remove,
  save: Save,
  search: Search,
  wrapText: WrapText,
};
