name: Playwright Tests
on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      working-directory: ./client
      run: npm ci

    - name: Install Playwright Browsers
      working-directory: ./client
      run: npx playwright install --with-deps

    - name: Install wait-on
      working-directory: ./client
      run: npm install wait-on

    - name: Run Playwright tests
      working-directory: ./client
      run: |
        npm run start & 
        npx wait-on http://localhost:3000
        npx playwright test
      
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
